[package]
name = "redisclient"
version = "0.1.1"
authors = ["liutao <liutao.rs@bytedance.com>"]
edition = "2018"
keywords = ["redis", "database"]
description = "Redis client for Rust"
repository = "https://github.com/ltoddy/redis-rs"
license = "MIT"
readme = "README.md"
