name: Redis client ci

on:
  push:
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
      - name: lint
        run: make lint
      - name: unittest
        run: make test
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
